[book]
title = "The Book of Learning"
authors = ["Rojesh Man Shikhrakar"]
language = "en"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
no-section-label=true
smart-punctuation = true
definition-lists = true
admonitions = true
input-404 = "not-found.md"
additional-css = ["theme/custom.css"]
sidebar-header-nav=true
mathjax-support = true


[output.html.fold]
enable = true
level = 0


[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
